def tool

pipeline {
    agent any;
    stages {
        stage("preBuild") {
            steps {
                script {
                    tool = load("automation/buildTool.groovy");
                    tool.preBuild();
                }
            }
        }

        stage("Import Header") { 
            steps {
                script {
                    tool.ImportHeader();
                }
            }
        }

        stage("Build") {
            steps {
                script {
                    tool.Build();
                }
            }

            post {
                always {
                    sh("rm -rf build | true")
                }
            }
        }

        stage("publish") {
            steps {
                script {
                    tool.publishToArtifactory();
                }
            }
        }
    }
}