def tool

pipeline {
    agent any;
    stages {
        stage("preBuild") {
            steps {
                script {
                    tool = load("automation/buildTool.groovy");
                    tool.preBuild();
                }
            }
        }

        stage("Build") {
            steps {
                script {
                    tool.Build();
                }
            }

            post {
                always {
                    sh("rm -rf build")
                }
            }
        }

        stage("Tests") {
            steps {
                script {
                    tool.deployTests();
                }
            }
        }
    }
}